version: "2"
services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    command: nginx -g "daemon off";

    depends_on:
      - nodejs

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: everfit-web-fake
